name = "aerofresh-etl"
main = "src/etl-scheduler.ts"
compatibility_date = "2024-09-01"

[env.production]
name = "aerofresh-etl-prod"
compatibility_date = "2024-09-01"

[env.staging]
name = "aerofresh-etl-staging"
compatibility_date = "2024-09-01"

# Environment variables
[vars]
ENV = "staging"

# Secrets (set via wrangler secret put)
# DATABASE_URL - PostgreSQL connection string with PostGIS
# AVWX_TOKEN - Aviation weather API token
# OPENSKY_USERNAME - OpenSky Network username
# OPENSKY_PASSWORD - OpenSky Network password

# Build configuration
[build]
command = "npm run build"

# KV namespaces for ETL state and caching
[[kv_namespaces]]
binding = "ETL_STATE"
id = "your-etl-state-kv-id"

[[kv_namespaces]]
binding = "ETL_CACHE"
id = "your-etl-cache-kv-id"

# R2 bucket for raw data storage
[[r2_buckets]]
binding = "RAW_DATA"
bucket_name = "aerofresh-raw-data"

# Queues for heavy processing
[[queues.producers]]
binding = "ETL_QUEUE"
queue = "etl-processing"

# Cron triggers for scheduled ETL jobs
[[triggers]]
crons = [
  "0 2 * * *",      # FAA Registry: Daily at 2 AM
  "0 3 * * 0",      # NTSB: Weekly on Sunday at 3 AM
  "0 */6 * * *",    # AD Directives: Every 6 hours
  "0 1 1 * *",      # OurAirports: Monthly on 1st at 1 AM
  "*/15 * * * *"    # Weather snapshots: Every 15 minutes
]
