# Deploy Web Application to Cloudflare Pages
# 
# Required GitHub Secrets:
# - CF_API_TOKEN: Cloudflare API token with Pages:Edit permissions
# - CF_ACCOUNT_ID: Your Cloudflare account ID
# 
# Optional GitHub Secrets (with fallbacks):
# - NEXT_PUBLIC_API_BASE_URL: API base URL (defaults to workers.dev URL)
# - MAPBOX_TOKEN: Mapbox API token for maps
# - SENTRY_DSN: Sentry error tracking DSN
# - POSTHOG_KEY: PostHog analytics key
#
# To set secrets: Repository Settings → Secrets and variables → Actions

name: Deploy Web (Cloudflare Pages)

on:
  push:
    branches: [ main ]
    paths: [ "apps/web/**", "packages/**" ]
  workflow_dispatch:

env:
  # Environment variables for secrets (reduces validation warnings)
  # NOTE: GitHub Actions editor shows warnings for unset secrets - this is EXPECTED
  # These warnings disappear once secrets are configured in repository settings
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL || 'https://aerofresh-api.your-subdomain.workers.dev' }}
  NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN || '' }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN || '' }}
  NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.POSTHOG_KEY || '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Validate required secrets
        run: |
          # Note: GitHub Actions editor shows warnings for unset secrets - this is expected
          # These warnings disappear once secrets are configured in repository settings
          if [ -z "$CF_API_TOKEN" ]; then
            echo "❌ CF_API_TOKEN secret is required but not set"
            exit 1
          fi
          if [ -z "$CF_ACCOUNT_ID" ]; then
            echo "❌ CF_ACCOUNT_ID secret is required but not set"
            exit 1
          fi
          echo "✅ Required secrets validated"
        
      - name: Build web application
        run: |
          cd apps/web
          pnpm build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          projectName: aerofresh-web
          directory: apps/web/.next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false
          
      - name: Update deployment status
        if: success()
        run: echo "✅ Web application deployed successfully to Cloudflare Pages"
        
      - name: Update deployment status
        if: failure()
        run: echo "❌ Web deployment failed"
